name: CI - Continuos Integration

on:
  pull_request:

jobs:
  build-and-test:
    name: React App Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node install
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Run tests
        run: npm test --watchAll=false
      
      - name: Build app
        run: npm run build