name: CI - Continuos Integration

on:
  pull_request:

jobs:
  build-and-test:
    name: Pipeline Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install

      - name: Execute tests
        run: npm test

      - name: Build app
        run: npm run build